exec-once = qs -c frameshell -d
exec-once = hypridle
exec-once = hyprsunset

$shell = qs -c frameshell ipc call shell

bind = SUPER, Space, exec, $shell launcher apps
bind = SUPER, T, exec, $shell launcher themes
bind = SUPER, F, exec, $shell launcher fonts
bind = SUPER, W, exec, $shell launcher wallpapers
bind = SUPER SHIFT, P, exec, $shell launcher session

bind = SUPER, D, exec, $shell drawer dashboard
bind = SUPER, Tab, exec, $shell drawer windows
bind = SUPER SHIFT, V, exec, $shell drawer clipboard

bind = SUPER, C, exec, $shell controls
bind = SUPER, A, exec, $shell agent
bind = SUPER, L, exec, $shell lock

bind = , Print, exec, $shell screenshot region
bind = SHIFT, Print, exec, $shell screenshot screen

misc {
    allow_session_lock_restore = true
}
